---
apiVersion: v1
kind: Namespace
metadata:
  name: networksim-system
  labels:
    name: networksim-system
    app.kubernetes.io/part-of: networksim
---
apiVersion: v1
kind: Namespace
metadata:
  name: networksim-sim
  labels:
    name: networksim-sim
    app.kubernetes.io/part-of: networksim
    # This label marks it as the chaos zone
    networksim.io/chaos-zone: "true"
